### ISSUE TITLE
Documentation link in readme is poor

### ISSUE THREAD

**Issue by djmattyg007** [zendframework/zend-permissions-rbac#13]
The documentation link in the readme points to a generic page that doesn't mention this package at all. It should point here instead: http://framework.zend.com/manual/current/en/modules/zend.permissions.rbac.intro.html

**Comment by IgorDePaula** [comment]
I agree, the documentation do not show how integrate this package with whole framework whit anothers components of framework.

**Comment by froschdesign** [comment]
@djmattyg007 
Please in the top bar, there can find the links to same content:

- [Intro](https://zendframework.github.io/zend-permissions-rbac/intro/)
- [Methods](https://zendframework.github.io/zend-permissions-rbac/methods/)
- [Examples](https://zendframework.github.io/zend-permissions-rbac/examples/)

@IgorDePaula 
Please open a new ticket for your problem.

**Comment by djmattyg007** [comment]
Obviously the readme hadn't been updated when I submitted this issue.
