### ISSUE TITLE
Rbac is unuseable

### ISSUE THREAD

**Issue by IgorDePaula** [zendframework/zend-permissions-rbac#15]
The rbac not has use with another components of framework like acl (on navigation component, by example).

How integrate it with another components?

**Comment by danizord** [comment]
Zend\Navigation does support RBAC since https://github.com/zendframework/zendframework/pull/3693

**Comment by danizord** [comment]
If you're looking for more integration (Doctrine, route guards, etc), take a look at [ZfcRbac](https://github.com/ZF-Commons/zfc-rbac).

**Comment by IgorDePaula** [comment]
The older and newer docs do not show how do. If the framework do not offer
native integration, please remove the component. I (others devs too) will
write my own.
Em 08/07/2016 11:16, "Daniel Gimenes" <notifications@github.com> escreveu:

**Comment by froschdesign** [comment]
> If the framework do not offer native integration…

This is not true.

> …please remove the component.

Really helpful your comment.

**Comment by froschdesign** [comment]
Closed in favor of #16

**Comment by IgorDePaula** [comment]
Is only this that you says?
Em 09/07/2016 05:10, "Frank Brückner" <notifications@github.com> escreveu:

**Comment by froschdesign** [comment]
> Is only this that you says?

Look at this: #16
