### ISSUE TITLE
Dynamic assertions + permission issue

### ISSUE THREAD

**Issue by ezimuel** [zendframework/zend-permissions-rbac#20]
The documentation about [dynamic assertion](https://zendframework.github.io/zend-permissions-rbac/intro/#dynamic-assertions) says: 

> In certain situations simply checking a permission key for access may not be enough. For example, assume two users, Foo and Bar, both have article.edit permission. What's to stop Bar from editing Foo's articles? The answer is dynamic assertions which allow you to specify extra runtime credentials that must pass for access to be granted.

From this description I would expect that the "extra runtime credentials" will be checked in parallel with the credentials but it seems that the [actual implementation](https://github.com/zendframework/zend-permissions-rbac/blob/master/src/Rbac.php#L140-L158) just bypass it.

According to the use case described before, I provided [here](https://gist.github.com/ezimuel/1592b30c9a4e94294c1707a178ddbe0e) a unit test to prove it. Basically, if Foo doesn't have the permission on article.edit and if the dymanic assertion is true the result is true (but should be false).

To fix this behaviour, in my opinion the dynamic assertion should be matched in AND with the permission. I provided a [gist here](https://gist.github.com/ezimuel/60a5f144ad5acd11e33afdcd0e6978e4).

**Comment by ezimuel** [comment]
@bakura10, @spiffyjr what do you think about this issue? /cc @weierophinney

**Comment by adrium** [comment]
I wrote the text below to zf-devteam on 21 Nov 2016 and @ezimuel replied. Unfortunately, I haven't had time to open a proper issue. I can now also provide a pull request, see #21.

There are two mentions of dynamic assertions in the documentation:

> The answer is dynamic assertions which allow you to specify
> extra runtime credentials that must pass for access to be granted.

https://github.com/zendframework/zend-permissions-rbac/blob/develop/doc/book/intro.md#dynamic-assertions

And:

> If $assert is provided and either an AssertInterface instance or callable,
> it will be queried before checking against the given role.

https://github.com/zendframework/zend-permissions-rbac/blob/develop/doc/book/methods.md#zendpermissionsrbacrbac

This conveys the impression, that somehow, the assertion and the
permission is checked. However, the implementation immediately returns
the result of the assertion without checking any roles for the
permission.

Why?

Actually, the $role and $permission parameters could be null, if the
$assert parameter is provided. The documentation mentions "extra
runtime credentials"  and "queried before checking", so the actual
behaviour is very counterintuitive.

**Comment by bakura10** [comment]
Hi,

Zend permissions Rbac is a bit broken and I'm not sure it's maintained anymore.

All the efforts has been put in ZfcRbac for some years now: https://github.com/ZF-Commons/zfc-rbac

**Comment by ezimuel** [comment]
@bakura10 what do you mean with "is a bit broken"? The component is still maintained by us, Zend Framework Team. 
Do you have something so say about this issue? If not, thanks anyway.

**Comment by bakura10** [comment]
I mean that the implementation was quite bad, inefficient and unflexible. I'm not sure many people are using this directly (as it is only a base implementation but require a higher level library like ZfcRbac). But ZfcRbac has not been based on this from many years now, but from another library I've developped in the past whose goal was to replaced this implementation.

I don't know how this library work unfortunately as I never really used it once I've found out it was too limited :(.

**Comment by ezimuel** [comment]
@bakura10 I tried to be professional in my previous comment but evidently you missed the point. If you don't have something to say related to the issue please don't say nothing. You cannot just say that sucks and suggest to move to a different project, especially if maintained by you, not really diplomatic. Even because your project started from this one. Don't forget where your bread's buttered, @bakura.

**Comment by weierophinney** [comment]
Admin note: deleted unrelated comments so we can keep discussion focused on the reported issue.

**Comment by spiffyjr** [comment]
@weierophinney Note: I haven't been doing much PHP for over a year but, if I recall correctly, the implementation by @ezimuel is actually correct. Dynamic assertion is a horrible name, but I digress. The result of the permission check **AND** the assertion should be valid if the assertion is provided.

**Comment by olegkrivtsov** [comment]
I'm trying to use `zend-permissions-rbac` in my project, but found this problem, too. Hope this will be fixed soon.

**Comment by ezimuel** [comment]
@spiffyjr thanks for your feedback. I'm going to merge #21.
