### ISSUE TITLE
Classmates, your module of the document written too bad! 

### ISSUE THREAD

**Issue by Dreamseekai** [zendframework/zend-permissions-rbac#28]
Classmates, your module of the document written too bad! I would like to know, if my authority stored in the database how to integrate this component? How even a database of examples are not? This document is too rubbish ~ ~ ~ delay time ~ Can you write documents carefully?

**Comment by Ocramius** [comment]
Closing as invalid, as the text is incomprehensible.

If you were referring to DB Integration, this component has none: it only provides the abstraction to perform RBAC access checks.

**Comment by weierophinney** [comment]
@Dreamseekai Please refer to our [code of conduct](https://github.com/zendframework/zend-permissions-rbac/blob/master/CONDUCT.md) before posting anything further.

Calling the work others have performed and that you get to use for free "rubbish", "bad", etc. is disrespectful.

If you have suggestions for improvement, please create _respectful_ issues indicating what changes you would like to see: improvements, fixes, additional examples, etc. Further, all documentation is itself part of the repository and written in markdown to facilitate contributions; see the [doc/book tree](https://github.com/zendframework/zend-permissions-rbac/blob/master/doc/book/) for the existing documentation.

**Comment by Ocramius** [comment]
I think the rudeness comes from an automated translator, and wasn't
intentional (see cross-linked issues)
