### ISSUE TITLE
getPermissions will only return the first permission

### ISSUE THREAD

**Issue by bakkerpeter** [zendframework/zend-permissions-rbac#38]
The method `getPermissions()` will only return the first permission of every role  due to the way it is written: 
` $permissions = (array) key($this->permissions);` [`Role::79`](https://github.com/zendframework/zend-permissions-rbac/blob/master/src/Role.php#L79)

My simple suggestion would be to fix this like this:
`$permissions = array_keys($this->permissions);`

Update: I've added a PR https://github.com/zendframework/zend-permissions-rbac/pull/39

**Comment by ezimuel** [comment]
Fixed in #39.
